sudo: required

language: cpp

addons:
  apt:
    packages:
      - bisonc++
      - python-setuptools

before_install:
  - sudo cp /etc/apt/sources.list /etc/apt/sources.list.d/trusty.list
  - sudo sed -i 's/precise/trusty/g' /etc/apt/sources.list.d/trusty.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y --force-yes flexc++ bisonc++ python-setuptools automake 
