sudo: required

language: cpp

addons:
  apt:
    packages:
      - bisonc++
      - python-setuptools

before_install:
    - sudo apt-get install -qq -y --force-yes flexc++ bisonc++ python-setuptools libprotobuf libjudy libpcap automake 
